### ISSUE TITLE
support other languages

### ISSUE THREAD

**Issue by kazu0617** [XDelta/NeosLogixCleanupWizard#1]
this mod seems only support english, so plz support other languages such as ja-jp

**Comment by XDelta** [comment]
I'll be changing up the method for adding the menu so that it isn't language specific or generally as brittle later today

**Comment by XDelta** [comment]
The wizard creation should now work regardless of language along with not potentially conflicting with other mods that add to the create new menu in [1.0.1](https://github.com/XDelta/NeosLogixCleanupWizard/releases/tag/1.0.1)
